-- Auto-generated by fetch_bars5s.py -- do not hand-edit.
-- Symbol/strategy are pulled from the fetch script's CONFIG block so
-- this file always matches the CSV in this folder. Runs against the
-- REPLAY database (livestreaming_replay).

-- Wipe exit_requests too: prepare_watchlist() merges armed exits into
-- the monitor set, so a stale row here (e.g. NVDA left over from a
-- previous run) would silently get monitored alongside SYMBOL.
TRUNCATE TABLE exit_requests;
TRUNCATE TABLE watchlist RESTART IDENTITY CASCADE;

WITH w AS (
    INSERT INTO watchlist (symbol)
    VALUES ('DELL')
    ON CONFLICT (symbol) DO UPDATE SET symbol = EXCLUDED.symbol
    RETURNING id
)
INSERT INTO watchlist_strategies (watchlist_id, strategy_name)
SELECT id, 'reversal_long' FROM w
ON CONFLICT (watchlist_id, strategy_name) DO NOTHING;
